import { useState, useEffect } from "react";
import axios from "axios";
import DashboardCard from "../components/DashboardCard";
import { FileText, Download, Eye } from "lucide-react";

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    axios
      .get("http://localhost:5000/api/reports")
      .then((res) => {
        setReports(res.data.reports || []);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Error fetching reports:", err);
        setLoading(false);
      });
  }, []);

  const reportTypeColors = {
    Security: "text-red-400 bg-red-900 bg-opacity-20",
    Performance: "text-blue-400 bg-blue-900 bg-opacity-20",
    Compliance: "text-green-400 bg-green-900 bg-opacity-20",
  };

  return (
    <div className="p-6 md:p-10">
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-white mb-2">Reports</h1>
        <p className="text-[#8892b0]">
          Access security, performance, and compliance reports generated by VigilantX.
        </p>
      </div>

      {loading ? (
        <div className="text-center text-[#8892b0] py-12 animate-pulse">
          Loading reports...
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-6">
          {/* Summary Section */}
          <DashboardCard title="Report Summary">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {["Security", "Performance", "Compliance"].map((type) => {
                const count = reports.filter((r) => r.type === type).length;
                const color =
                  type === "Security"
                    ? "text-red-400 bg-red-900 bg-opacity-20 border border-red-800"
                    : type === "Performance"
                    ? "text-blue-400 bg-blue-900 bg-opacity-20 border border-blue-800"
                    : "text-green-400 bg-green-900 bg-opacity-20 border border-green-800";
                return (
                  <div key={type} className={`p-4 rounded-lg ${color}`}>
                    <p className="text-sm font-medium">{type}</p>
                    <p className="text-3xl font-bold text-white">{count}</p>
                  </div>
                );
              })}
            </div>
          </DashboardCard>

          {/* All Reports */}
          <DashboardCard title="All Reports">
            {reports.length > 0 ? (
              <div className="space-y-3">
                {reports.map((report, index) => (
                  <div
                    key={index}
                    className="p-4 bg-[#0a192f] rounded-lg border border-[#233554] hover:border-[#64ffda] transition-all"
                  >
                    <div className="flex items-center justify-between gap-4">
                      <div className="flex items-center gap-4 flex-1">
                        <FileText className="w-6 h-6 text-[#64ffda]" />
                        <div className="flex-1">
                          <h3 className="text-[#ccd6f6] font-semibold">
                            {report.name.replace(/_/g, " ")}
                          </h3>
                          <p className="text-[#8892b0] text-sm">
                            Generated: {report.generated_at}
                          </p>
                        </div>
                        <span
                          className={`px-3 py-1 rounded-full text-xs font-medium capitalize ${
                            reportTypeColors[report.type]
                          }`}
                        >
                          {report.type}
                        </span>
                      </div>

                      <div className="flex items-center gap-2">
                        <a
                          href={report.view_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="p-2 text-[#8892b0] hover:text-[#64ffda] hover:bg-[#1a2a42] rounded-lg transition"
                          title={`View ${report.format}`}
                        >
                          <Eye className="w-5 h-5" />
                        </a>

                        <a
                          href={report.download_url}
                          download
                          className="p-2 text-[#8892b0] hover:text-[#64ffda] hover:bg-[#1a2a42] rounded-lg transition"
                          title={`Download ${report.format}`}
                        >
                          <Download className="w-5 h-5" />
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-gray-400">No reports available yet.</p>
            )}
          </DashboardCard>
        </div>
      )}
    </div>
  );
}
